# -*- coding: utf-8 -*-
"""Random_Password_Genrator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJukVgaOhHSjhOTM5Mtq_PaeOr1f3GOa

# 🎲 Random Project Generator

Description

A simple Python program that generates random project ideas to help students and beginners get started with new projects.

Features

->Generates random project ideas

->Easy to use

->Beginner-friendly
"""

import random
import string

def generate_password():

    # Generate a random password based on user specifications

    print("=== Random Password Generator ===\n")

    while True:
        try:
            length = int(input("Enter the desired password length: "))
            if length < 1:
                print("Password length must be at least 1. Please try again.")
                continue
            break
        except ValueError:
            print("Please enter a valid number.")

    while True:
        try:
            num_alphabets = int(input("Enter number of alphabets: "))
            if num_alphabets < 0:
                print("Number of alphabets cannot be negative.")
                continue
            break
        except ValueError:
            print("Please enter a valid number.")

    while True:
        try:
            num_digits = int(input("Enter number of digits: "))
            if num_digits < 0:
                print("Number of digits cannot be negative.")
                continue
            break
        except ValueError:
            print("Please enter a valid number.")

    while True:
        try:
            num_special = int(input("Enter number of special characters: "))
            if num_special < 0:
                print("Number of special characters cannot be negative.")
                continue
            break
        except ValueError:
            print("Please enter a valid number.")

    total_specified = num_alphabets + num_digits + num_special
    if total_specified > length:
        print(f"\nError: Total specified characters ({total_specified}) exceeds password length ({length})!")
        return None


    alphabets = string.ascii_letters
    digits = string.digits
    special_chars = "!@#$%^&*_+-=|;:,.<>?"


    password_chars = []

    for _ in range(num_alphabets):
        password_chars.append(random.choice(alphabets))

    for _ in range(num_digits):
        password_chars.append(random.choice(digits))

    for _ in range(num_special):
        password_chars.append(random.choice(special_chars))

    remaining_length = length - total_specified
    all_chars = alphabets + digits + special_chars

    for _ in range(remaining_length):
        password_chars.append(random.choice(all_chars))


    random.shuffle(password_chars)

    password = ''.join(password_chars)

    return password

def main():

    #Main function to run the password generator

    while True:
        password = generate_password()

        if password:
            print(f"\nGenerated Password: {password}")
            print(f"Password Length: {len(password)}")

            alphabets_count = sum(1 for c in password if c.isalpha())
            digits_count = sum(1 for c in password if c.isdigit())
            special_count = sum(1 for c in password if not c.isalnum())

            print("\nPassword Composition:")
            print(f"Alphabets: {alphabets_count}")
            print(f"Digits: {digits_count}")
            print(f"Special Characters: {special_count}")

        while True:
            choice = input("\nDo you want to generate another password? (y/n): ").lower().strip()
            if choice in ['y', 'yes']:
                print()
                break
            elif choice in ['n', 'no']:
                print("Thank you for using the Password Generator!")
                return
            else:
                print("Please enter 'y' for yes or 'n' for no.")

if __name__ == "__main__":
    main()